# -*- coding: utf-8 -*-
"""LR_1_task_6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_MrER3MRSOEdfi58wb0mdpn5TPIY_N_F
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
data = pd.read_csv('data_multivar_nb.txt', header=None)
data.columns = [f'feature_{i}' for i in range(data.shape[1]-1)] + ['label']
print("Дані завантажено:")
print(data.head(), '\n')
X = data.drop(columns=['label'])
y = data['label']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
svm_model = SVC(kernel='linear')
svm_model.fit(X_train, y_train)
y_pred_svm = svm_model.predict(X_test)
nb_model = GaussianNB()
nb_model.fit(X_train, y_train)
y_pred_nb = nb_model.predict(X_test)
def evaluate_model(model_name, y_true, y_pred):
    """Функція для оцінки результатів моделей."""
    print(f"\nРезультати {model_name}:")
    print("Матриця плутанини:")
    print(confusion_matrix(y_true, y_pred))
    print("\nКласифікаційний звіт:")
    print(classification_report(y_true, y_pred))
    print(f"Точність ({model_name}): {accuracy_score(y_true, y_pred):.3f}\n")
evaluate_model("Support Vector Machine", y_test, y_pred_svm)
evaluate_model("Naive Bayes", y_test, y_pred_nb)
svm_accuracy = accuracy_score(y_test, y_pred_svm)
nb_accuracy = accuracy_score(y_test, y_pred_nb)
better_model = "Support Vector Machine" if svm_accuracy > nb_accuracy else "Naive Bayes"
print(f"\nВисновок: Модель {better_model} краще класифікує дані.")